config/routes.rb
Rails.application.routes.draw do
  
  root 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :quantities

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
   has_many :quantities, dependent: :destroy
   has_many :recipes, through: :quantities
   #validates_presence_of :name
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
   belongs_to :recipe
   belongs_to :ingredient
   #validates_presence_of :recipe_id, :ingredient_id, :amount
   accepts_nested_attributes_for :ingredient, reject_if: :all_blank, :allow_destroy => true
   
   delegate :name, :price, to: :ingredient, prefix: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
   has_many :quantities, dependent: :destroy
   has_many :ingredients, through: :quantities, dependent: :destroy, :class_name => 'Ingredient'
   validates_presence_of :name
   #accepts_nested_attributes_for :ingredients
   accepts_nested_attributes_for :quantities, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
   
   def index
       
   end
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   
   def index
       @recipes = Recipe.all
   end
   
   def new
      @recipe = Recipe.new 
      
   end
   
   def create
      @recipe = Recipe.new(recipe_params)
    if @recipe.save
        redirect_to recipes_path
    else
        render 'new'
    end
   end
   
   def edit
      @recipe = Recipe.find(params[:id]) 
   end
   
   def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
        redirect_to recipes_path
    else
        render 'edit'
    end
   end
   
   def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Recipe was successfully deleted"
    redirect_to recipes_path
   end
   
   def recipe_params
      params.require(:recipe).permit(:name, quantities_attributes: [:id, :recipe_id, :ingredient_id, :amount, :_destroy, ingredient_attributes: [:id, :name, :price, :_destroy]]) 
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = "col-md-10">
    <%= yield %>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<% end %>


<%= form_for @recipe, html: {class: "form-group"} do |f| %>
    <%= f.label :recipe_name %>
    <%= f.text_field :name, required: true, class: "form-control" %>
    <table>
        <thead>
            <tr>
                <th>Quantity</th>
                <th>Name</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody class = "quantities">
            <%= f.fields_for :quantities do |g| %>
                <%#= render 'quantity_fields', f: g %>
                <tr class = "existing-fields nested-fields">
                    
                        <%= g.fields_for :ingredient do |h| %>
                            <td><%= g.number_field :amount, class: "form-control" %></td>
                            <td><%= h.text_field :name, class: "form-control price_text" %></td>
                            <td><%= h.number_field :price, class: "form-control price_text" %></td>
                        <% end %>
                    
                    <td><%= link_to_remove_association "Remove", g %></td>
                        
                </tr> 
                
            <% end %>
            <div class = "links">
                <%= link_to_add_association "Add", f, :quantities, data: {"association-insertion-node" => "tbody.quantities", "association-insertion-method" => "append"} %>
            </div>
        </tbody>
    </table>
    
    
    <br>
    <%= f.submit %>
<% end %>

<script>
     $('.recipe_select').on('change', function(){
         var value = $(this).closest(".existing-fields");
         //alert($(this).find(":selected").attr("data-price"));
         $(value).find('.price_text').val($(this).find(":selected").attr("data-price"));
         
     });
</script>

app/views/recipes/_ingredient_fields.html.erb
<td class="nested-fields">
    <%= f.text_field :name, required: true, class: "form-control" %>
</td>
<td class="nested-fields">
    <%= f.number_field :price, required: true, class: "form-control" %>
</td>
<td><%= link_to_remove_association "Remove", f %></td>

app/views/recipes/_quantity_fields.html.erb
<tr class = "nested-fields quantity-fields">
    <td class = "quantity"><%= f.number_field :amount, required: true, class: "form-control" %></td>
    <td class= "ingredient_from_list">
        <%#= f.collection_select :ingredient_id, Ingredient.order(:name), :id, :name, {prompt: "Select an ingredient"}, {class: 'recipe_select form-control'} %>
        <%= f.select(:ingredient_id, Ingredient.order(:name).map{|a| [a.name, a.id, {'data-price' => a.price}]}, {prompt: "Select an ingredient"}, {class: 'recipe_select form-control'}) %>
        <%#= f.association :ingredient, collection: Ingredients.all(:order => 'name').map { |g| [g.name, g.id, {'data-price' => g.price}] }, :prompt => 'Choose an existing ingredient', label: false, input_html: {class:'form-control recipe_select', id:'recipe_select' } %>
        <%#= f.association :ingredient_id, options_from_collection_for_select(Ingredient.order(:name).map{|a| [a.name, a.id, {'data-price' => a.price}]}, {prompt: "Select an ingredient"}, {class: 'recipe_select form-control'}, :id, :name, @recipe.ingredient_id) %>
    </td>
    <td class="remove"><input type="text" class="form-control price_text" disabled></td>
    <td class="remove"><%#= link_to_add_association 'or create new', f, :ingredient, data: {"association-insertion-node" => "tr.nested-fields", "association-insertion-traversal" => "closest", "association-insertion-method" => "prepend"}  %>
    <%= link_to_add_association 'or create new', f, :ingredient, data: {"association-insertion-node" => "tr.nested-fields", "association-insertion-traversal" => "closest", "association-insertion-method" => "append"}  %>
    </td>
    <td class="remove"><%= link_to_remove_association "Remove", f %></td>
</tr> 

<script>
     $('.recipe_select').on('change', function(){
         var value = $(this).closest(".nested-fields");
         //alert($(this).find(":selected").attr("data-price"));
         $(value).find('.price_text').val($(this).find(":selected").attr("data-price"));
     });
</script>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>List of Recipes <%= link_to 'Create', new_recipe_path, class: "btn btn-primary" %></h1>



    <% @recipes.each do |recipe| %>
    <div class = "col-md-3">
        <div class = "card" style = "width: 40rem;">
            <div class = "card-block">
                <% recipe = Recipe.includes(:quantities).find(recipe.id) %>
                <h4><%= recipe.name %></h4>
                <p class = "card-text">Ingredients</p>
                <table class = "table">
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                    <% recipe.quantities.each do |f| %>
                        <tr>
                            <td><%= f.ingredient_name %></td>
                            <td><%= f.amount %></td>
                            <td><%= number_to_currency(f.ingredient_price) %></td>
                        </tr>
                    <% end %>
                </table>
                    <%= link_to 'Edit', edit_recipe_path(recipe.id), class: "btn btn-primary" %>
                    <%= link_to 'Delete', recipe_path(recipe), :method => 'delete', data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
            </div>
        </div>   
    </div>
    
    <% end %>

app/views/recipes/new.html.erb
<%= render 'form' %>